### PR TITLE
fix compatibilities when BUILD_DIR argument is /app

### LINKED ISSUE #194: Buildpack incompatible with building in /app
Hi

I'm on the team that maintains Heroku's build system and official buildpacks, and wanted to let you know about a future incompatibility with this buildpack.

The directory in which the Heroku build system performs builds is currently a path like`/tmp/build_<hash>`.

In the near future this path will be changing to `/app` so that the build-time and run-time app locations are the same path - in order to resolve a number of long standing bugs and reduce the number of hacks buildpacks have to use to work around non-relocatable languages/toolchains. As part of this change, `HOME` will also be changing from `/app` to a PATH under `/tmp` (otherwise temporary files/secrets saved to HOME would end up in the slug).

Trying out the above change with this buildpack (using [this sample app](https://github.com/HashNuke/heroku-buildpack-elixir-test) and `heroku labs:enable build-in-app-dir`) revealed that builds with this buildpack will break - or more accurately, output an error to the build log, however the build be incorrectly marked as successful and instead the app give a boot time error.

Build time error:

```
remote: -----> Building on the Heroku-20 stack
remote: -----> Performing build in /app since 'build-in-app-dir' is enabled
remote: -----> Elixir app detected
remote: -----> Will export the following config vars:
remote:        * MIX_ENV=prod
remote: -----> Checking Erlang and Elixir versions
remote:        WARNING: elixir_buildpack.config wasn't found in the app
remote:        Using default config from Elixir buildpack
remote:
remote:        IMPORTANT: The default elixir_version will be removed on 2021-06-01. Please explicitly set an elixir_version in your elixir_buildpack.config before then or your deploys will fail.
remote:
remote:        Will use the following versions:
remote:        * Stack heroku-20
remote:        * Erlang 20.1
remote:        * Elixir v1.5.3
remote: -----> Using cached Erlang 20.1
remote: -----> Installing Erlang 20.1
remote:
remote: cp: will not create hard link '/app/.platform_tools/erlang/erlang/erlang' to directory '/app/.platform_tools/erlang/erlang'
remote: -----> Using cached Elixir v1.5.3
...
```

Then at boot:

```
2021-03-14T18:56:25.000000+00:00 app[api]: Build succeeded
2021-03-14T18:56:26.039686+00:00 app[web.1]: /app/.platform_tools/elixir/bin/elixir: 127: exec: erl: not found
2021-03-14T18:56:26.117294+00:00 heroku[web.1]: Process exited with status 127
2021-03-14T18:56:26.191815+00:00 heroku[web.1]: State changed from starting to crashed
```

It appears there are two issues:
1. Errors during the build don't cause the build to fail (not using Bash exit on error)
2. The file removals, hardlink and copy here need to take into account that the BUILD_DIR might be `/app`: https://github.com/HashNuke/heroku-buildpack-elixir/blob/b9092d471ebb0163dbf1bf733b719cf1e31c8f64/lib/erlang_funcs.sh#L29-L38

We're hoping to enable the new build behaviour very soon - and whilst there will be an opt-out labs, it would be great to get this resolved before then to prevent Erlang apps from failing to boot after the first build, for users that miss the Heroku changelog entry etc.

Many thanks :-)

### PR DESCRIPTION
**Pull request by fivetanley**
fixes #194

Newer versions of the Heroku build system build the app in `/app` rather
than a tmp directory. If this is the case (the BUILD_DIR argument is the
same as `/app`), don't copy hex or other files over as they are already
in place.

https://github.com/HashNuke/heroku-buildpack-elixir/issues/194#issuecomment-800425532

### CODE REVIEW

File: lib/app_funcs.sh [hunk 1]
```diff
@@ -17,6 +17,12 @@ function copy_hex() {
   mkdir -p ${build_path}/.mix/archives
   mkdir -p ${build_path}/.hex
 
+  # copying hex is not necessary on the new build system,
+  # which builds in /app (which is the same as $HOME)
+  # https://github.com/HashNuke/heroku-buildpack-elixir/issues/194
+  if [ ${HOME} == ${build_path} ]; then
```
Comment (edmorley) [inline lib/app_funcs.sh:23]: With the upcoming build system changes (currently opt in via the `` labs), `$HOME` will no longer be `/app` at build time (but will remain `/app` at runtime):

> As part of this change, HOME will also be changing from /app to a PATH under /tmp (otherwise temporary files/secrets saved to HOME would end up in the slug).
> https://github.com/HashNuke/heroku-buildpack-elixir/issues/194

If this function is running at build time, it needs to use `/app` (or `runtime_erlang_path`) rather than `$HOME` in this comparison.

**Review by edmorley — COMMENTED** [review]
Thank you for looking at this!

**Comment by edmorley** [comment]
This was reverted in #202, since it needed the above review changes before merging unfortunately.
